# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentop < Formula
  desc "Terminal dashboard for AI coding assistant sessions — token usage, cost, and cache efficiency"
  homepage "https://github.com/mohitmishra786/agentop"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mohitmishra786/agentop/releases/download/v0.1.2/agentop_0.1.2_darwin_x86_64.tar.gz"
      sha256 "43851b2e2c764a32eea39fc4bfb7ede0c9c6fc06939a1e31bca7ff76857f0ecf"

      define_method(:install) do
        bin.install "agentop"
        man1.install "agentop.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mohitmishra786/agentop/releases/download/v0.1.2/agentop_0.1.2_darwin_arm64.tar.gz"
      sha256 "a55c3b5e7daf7078bbba9b2149c0284f65dc2a6627095882339a5cafc342a222"

      define_method(:install) do
        bin.install "agentop"
        man1.install "agentop.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohitmishra786/agentop/releases/download/v0.1.2/agentop_0.1.2_linux_x86_64.tar.gz"
      sha256 "601050dc2dea9396b4b49812a6a8ead5a804d35bd9b84f6e2163e1931b804da8"
      define_method(:install) do
        bin.install "agentop"
        man1.install "agentop.1"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mohitmishra786/agentop/releases/download/v0.1.2/agentop_0.1.2_linux_armv6.tar.gz"
      sha256 "7c7cfeceb06592c3040f8297fd4c0f9813de82e0281c99cba43c7476ea07a3c2"
      define_method(:install) do
        bin.install "agentop"
        man1.install "agentop.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohitmishra786/agentop/releases/download/v0.1.2/agentop_0.1.2_linux_arm64.tar.gz"
      sha256 "80bf672bc3805e3b25a836bbbfc118f34d2eeb9ec8cbeeefaa05d8a6ee1c11ab"
      define_method(:install) do
        bin.install "agentop"
        man1.install "agentop.1"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentop --version")
  end
end
