# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentop < Formula
  desc "Terminal dashboard for AI coding assistant sessions — token usage, cost, and cache efficiency"
  homepage "https://github.com/mohitmishra786/agentop"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mohitmishra786/agentop/releases/download/v1.0.0/agentop_1.0.0_darwin_x86_64.tar.gz"
      sha256 "0e646f3c5671d9700261ca1a7848254b927c775dd1b24d82c7fb59c705d6c324"

      define_method(:install) do
        bin.install "agentop"
        man1.install "agentop.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mohitmishra786/agentop/releases/download/v1.0.0/agentop_1.0.0_darwin_arm64.tar.gz"
      sha256 "f5413440f2a2a4c24640a2301a48e13bd129f28db860a4fd8bab566cc81cc6d2"

      define_method(:install) do
        bin.install "agentop"
        man1.install "agentop.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohitmishra786/agentop/releases/download/v1.0.0/agentop_1.0.0_linux_x86_64.tar.gz"
      sha256 "1b02b15f7fb85992d12d6efaa6607bb7cce3edde56b56257b267df58a9a36d49"
      define_method(:install) do
        bin.install "agentop"
        man1.install "agentop.1"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mohitmishra786/agentop/releases/download/v1.0.0/agentop_1.0.0_linux_armv6.tar.gz"
      sha256 "fe487e19b3703cdc4ecf60e829d95f7cdec780a41b0bc2878428fc0049fbdc09"
      define_method(:install) do
        bin.install "agentop"
        man1.install "agentop.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohitmishra786/agentop/releases/download/v1.0.0/agentop_1.0.0_linux_arm64.tar.gz"
      sha256 "89b10c4b15e25460d378b835f5d11b8a5dd3847720843111d7cd588b43bbbc4d"
      define_method(:install) do
        bin.install "agentop"
        man1.install "agentop.1"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentop --version")
  end
end
