# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdmend < Formula
  desc "Fix Markdown lint violations across all files, instantly."
  homepage "https://github.com/mohitmishra786/mdmend"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mohitmishra786/mdmend/releases/download/v1.0.1/mdmend_1.0.1_darwin_amd64.tar.gz"
      sha256 "ebfe75adce36b76ab1326dbe2a9660c2c66bdbcd0b897f46367271a59b6eb09c"

      define_method(:install) do
        bin.install "mdmend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mohitmishra786/mdmend/releases/download/v1.0.1/mdmend_1.0.1_darwin_arm64.tar.gz"
      sha256 "96225c8fd380ebb92f6db1a8c3231e019c2c75723fb04022be98605463f0c1f7"

      define_method(:install) do
        bin.install "mdmend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohitmishra786/mdmend/releases/download/v1.0.1/mdmend_1.0.1_linux_amd64.tar.gz"
      sha256 "18f466b13d9f4c4e928952c357ee1dc7149fc954d808fe9c44feb425b675e8e0"
      define_method(:install) do
        bin.install "mdmend"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohitmishra786/mdmend/releases/download/v1.0.1/mdmend_1.0.1_linux_arm64.tar.gz"
      sha256 "ba798e4a77b087bfc612372671501f0bdb17a8b974ee01ab3624f86b8a602635"
      define_method(:install) do
        bin.install "mdmend"
      end
    end
  end

  test do
    system "#{bin}/mdmend --version"
  end
end
